In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv("bigdatamartsales.csv")

In [3]:
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [4]:
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Item_Weight,7060.0,12.857645,4.643456,4.555,8.773750,12.600000,16.850000,21.350000
Item_Visibility,8523.0,0.066132,0.051598,0.000,0.026989,0.053931,0.094585,0.328391
Item_MRP,8523.0,140.992782,62.275067,31.290,93.826500,143.012800,185.643700,266.888400
Outlet_Establishment_Year,8523.0,1997.831867,8.371760,1985.000,1987.000000,1999.000000,2004.000000,2009.000000
Item_Outlet_Sales,8523.0,2181.288914,1706.499616,33.290,834.247400,1794.331000,3101.296400,13086.964800

In [6]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
le=LabelEncoder()
list1=['Item_Identifier','Item_Fat_Content','Item_Type','Outlet_Identifier','Outlet_Location_Type','Outlet_Type','Outlet_Size']
for val in list1:
    df[val]=le.fit_transform(df[val].astype(str))

In [9]:
df.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,156,9.300,1,0.016047,4,249.8092,9,1999,1,0,1,3735.1380
1,8,5.920,2,0.019278,14,48.2692,3,2009,1,2,2,443.4228
2,662,17.500,1,0.016760,10,141.6180,9,1999,1,0,1,2097.2700
3,1121,19.200,2,0.000000,6,182.0950,0,1998,3,2,0,732.3800
4,1297,8.930,1,0.000000,9,53.8614,1,1987,0,2,1,994.7052
5,758,10.395,2,0.000000,0,51.4008,3,2009,1,2,2,556.6088
6,696,13.650,2,0.012741,13,57.6588,1,1987,0,2,1,343.5528
7,738,NaN,1,0.127470,13,107.7622,5,1985,1,2,3,4022.7636
8,440,16.200,2,0.016687,5,96.9726,7,2002,3,1,1,1076.5986
9,990,19.200,2,0.094450,5,187.8214,2,2007,3,1,1,4710.5350
10,1171,11.800,1,0.000000,6,45.5402,9,1999,1,0,1,1516.0266
11,147,18.500,2,0.045464,4,144.1102,8,1997,2,0,1,2187.1530
12,1142,15.100,2,0.100014,6,145.4786,9,1999,1,0,1,1589.2646
13,904,17.600,2,0.047257,13,119.6782,8,1997,2,0,1,2145.2076
14,375,16.350,1,0.068024,6,196.4426,1,1987,0,2,1,1977.4260
15,767,9.000,2,0.069089,2,56.3614,8,1997,2,0,1,1547.3192
16,1280,11.800,1,0.008596,8,115.3492,3,2009,1,2,2,1621.8888
17,767,9.000,2,0.069196,2,54.3614,9,1999,1,0,1,718.3982
18,79,NaN,1,0.034238,7,113.2834,5,1985,1,2,3,2303.6680
19,968,13.350,1,0.102492,4,230.5352,6,2004,2,1,1,2748.4224

In [10]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [11]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer( missing_values=np.NaN,strategy='mean')
df['Item_Weight']=imp.fit_transform(df['Item_Weight'].values.reshape(-1,1))[:,0]
print(df)

      Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  \
0                 156        9.300                 1         0.016047
1                   8        5.920                 2         0.019278
2                 662       17.500                 1         0.016760
3                1121       19.200                 2         0.000000
4                1297        8.930                 1         0.000000
...               ...          ...               ...              ...
8518              370        6.865                 1         0.056783
8519              897        8.380                 2         0.046982
8520             1357       10.600                 1         0.035186
8521              681        7.210                 2         0.145221
8522               50       14.800                 1         0.044878

      Item_Type  Item_MRP  Outlet_Identifier  Outlet_Establishment_Year  \
0             4  249.8092                  9                       1999
1            14   48.2692                  3                       2009
2            10  141.6180                  9                       1999
3             6  182.0950                  0                       1998
4             9   53.8614                  1                       1987
...         ...       ...                ...                        ...
8518         13  214.5218                  1                       1987
8519          0  108.1570                  7                       2002
8520          8   85.1224                  6                       2004
8521         13  103.1332                  3                       2009
8522         14   75.4670                  8                       1997

      Outlet_Size  Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales
0               1                     0            1          3735.1380
1               1                     2            2           443.4228
2               1                     0            1          2097.2700
3               3                     2            0           732.3800
4               0                     2            1           994.7052
...           ...                   ...          ...                ...
8518            0                     2            1          2778.3834
8519            3                     1            1           549.2850
8520            2                     1            1          1193.1136
8521            1                     2            2          1845.5976
8522            2                     0            1           765.6700

[8523 rows x 12 columns]

In [12]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [13]:
df.skew()

Item_Identifier             -0.008877
Item_Weight                  0.090561
Item_Fat_Content             0.994824
Item_Visibility              1.167091
Item_Type                    0.101655
Item_MRP                     0.127202
Outlet_Identifier           -0.059861
Outlet_Establishment_Year   -0.396641
Outlet_Size                 -0.131895
Outlet_Location_Type        -0.209093
Outlet_Type                  0.927438
Item_Outlet_Sales            1.177531
dtype: float64

In [14]:
df.corr()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Identifier,1.000000,0.044518,-0.098114,-0.025482,-0.017973,0.012853,-0.008602,-0.012772,0.000855,0.003656,-0.001178,0.002869
Item_Weight,0.044518,1.000000,-0.017331,-0.012049,0.028015,0.024756,-0.007975,-0.008301,-0.015096,0.004088,-0.000566,0.011550
Item_Fat_Content,-0.098114,-0.017331,1.000000,0.034042,-0.115958,-0.000876,-0.002357,-0.000189,-0.004795,-0.004102,-0.004214,0.009800
Item_Visibility,-0.025482,-0.012049,0.034042,1.000000,-0.035249,-0.001315,-0.100439,-0.074834,0.087796,-0.028099,-0.173468,-0.128625
Item_Type,-0.017973,0.028015,-0.115958,-0.035249,1.000000,0.032651,0.001656,0.004970,0.000827,0.003084,0.003053,0.017048
Item_MRP,0.012853,0.024756,-0.000876,-0.001315,0.032651,1.000000,0.003319,0.005020,-0.002473,0.000232,-0.001975,0.567574
Outlet_Identifier,-0.008602,-0.007975,-0.002357,-0.100439,0.001656,0.003319,1.000000,0.079035,0.053224,-0.716176,0.099873,0.162325
Outlet_Establishment_Year,-0.012772,-0.008301,-0.000189,-0.074834,0.004970,0.005020,0.079035,1.000000,0.470343,-0.089216,-0.122304,-0.049135
Outlet_Size,0.000855,-0.015096,-0.004795,0.087796,0.000827,-0.002473,0.053224,0.470343,1.000000,-0.290216,-0.432062,-0.172477
Outlet_Location_Type,0.003656,0.004088,-0.004102,-0.028099,0.003084,0.000232,-0.716176,-0.089216,-0.290216,1.000000,0.467219,0.089367
Outlet_Type,-0.001178,-0.000566,-0.004214,-0.173468,0.003053,-0.001975,0.099873,-0.122304,-0.432062,0.467219,1.000000,0.401522
Item_Outlet_Sales,0.002869,0.011550,0.009800,-0.128625,0.017048,0.567574,0.162325,-0.049135,-0.172477,0.089367,0.401522,1.000000

In [15]:
from scipy.stats import zscore
z_score=abs(zscore(df))
print(df.shape)
df1=df.loc[(z_score<3).all(axis=1)]
print(df1.shape)

(8523, 12)
(8222, 12)

In [16]:
df1.skew()

Item_Identifier             -0.011945
Item_Weight                  0.087821
Item_Fat_Content             0.291106
Item_Visibility              0.794506
Item_Type                    0.094578
Item_MRP                     0.139153
Outlet_Identifier           -0.067611
Outlet_Establishment_Year   -0.420927
Outlet_Size                 -0.131316
Outlet_Location_Type        -0.202794
Outlet_Type                  0.957163
Item_Outlet_Sales            0.877476
dtype: float64

In [17]:
df.corr()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Identifier,1.000000,0.044518,-0.098114,-0.025482,-0.017973,0.012853,-0.008602,-0.012772,0.000855,0.003656,-0.001178,0.002869
Item_Weight,0.044518,1.000000,-0.017331,-0.012049,0.028015,0.024756,-0.007975,-0.008301,-0.015096,0.004088,-0.000566,0.011550
Item_Fat_Content,-0.098114,-0.017331,1.000000,0.034042,-0.115958,-0.000876,-0.002357,-0.000189,-0.004795,-0.004102,-0.004214,0.009800
Item_Visibility,-0.025482,-0.012049,0.034042,1.000000,-0.035249,-0.001315,-0.100439,-0.074834,0.087796,-0.028099,-0.173468,-0.128625
Item_Type,-0.017973,0.028015,-0.115958,-0.035249,1.000000,0.032651,0.001656,0.004970,0.000827,0.003084,0.003053,0.017048
Item_MRP,0.012853,0.024756,-0.000876,-0.001315,0.032651,1.000000,0.003319,0.005020,-0.002473,0.000232,-0.001975,0.567574
Outlet_Identifier,-0.008602,-0.007975,-0.002357,-0.100439,0.001656,0.003319,1.000000,0.079035,0.053224,-0.716176,0.099873,0.162325
Outlet_Establishment_Year,-0.012772,-0.008301,-0.000189,-0.074834,0.004970,0.005020,0.079035,1.000000,0.470343,-0.089216,-0.122304,-0.049135
Outlet_Size,0.000855,-0.015096,-0.004795,0.087796,0.000827,-0.002473,0.053224,0.470343,1.000000,-0.290216,-0.432062,-0.172477
Outlet_Location_Type,0.003656,0.004088,-0.004102,-0.028099,0.003084,0.000232,-0.716176,-0.089216,-0.290216,1.000000,0.467219,0.089367
Outlet_Type,-0.001178,-0.000566,-0.004214,-0.173468,0.003053,-0.001975,0.099873,-0.122304,-0.432062,0.467219,1.000000,0.401522
Item_Outlet_Sales,0.002869,0.011550,0.009800,-0.128625,0.017048,0.567574,0.162325,-0.049135,-0.172477,0.089367,0.401522,1.000000

In [18]:
#seprating target and input variable
df1_x=df1.drop(columns=['Item_Outlet_Sales'])
y=df1[['Item_Outlet_Sales']]

In [19]:
#scaling the input variables for linear regression algo
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(df1_x)
x=pd.DataFrame(x,columns=df1_x.columns)

In [20]:
#check the skewness again
x.skew()

Item_Identifier             -0.011945
Item_Weight                  0.087821
Item_Fat_Content             0.291106
Item_Visibility              0.794506
Item_Type                    0.094578
Item_MRP                     0.139153
Outlet_Identifier           -0.067611
Outlet_Establishment_Year   -0.420927
Outlet_Size                 -0.131316
Outlet_Location_Type        -0.202794
Outlet_Type                  0.957163
dtype: float64

# TESTING

In [21]:
from sklearn.model_selection import train_test_split

In [ ]:
 from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn import linear_model
max_r_score=0
for r_state in range(42,100):
    x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=r_state,test_size=0.20)
    reg=linear_model.LinearRegression()
    reg.fit(x_train,y_train)
    y_pred=reg.predict(x_test)
    r2_scr=r2_score(y_test,y_pred)
    if r2_scr>max_r_score:
        max_r_score=r2_scr
        final_r_state=r_state
        
print("maxr2 score",final_r_state,"is",max_r_score)

# Linear Regression

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(linear_model.LinearRegression(),x,y,cv=10,scoring="r2").mean()

0.486603891121436

In [24]:
cross_val_score(linear_model.LinearRegression(),x,y,cv=10,scoring="r2")

array([0.5002306 , 0.49678654, 0.47871291, 0.51042581, 0.44663074,
       0.4918129 , 0.51300552, 0.46186839, 0.50020032, 0.46636519])

In [25]:
from sklearn.metrics import confusion_matrix

In [31]:
#max r2 score we get random state 92
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=92,test_size=0.25)

reg=linear_model.LinearRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)

In [32]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print("r2 score is:",r2_score(y_test,y_pred))
print("RMSE is",np.sqrt(mean_squared_error(y_test,y_pred)))

r2 score is: 0.4951011126884469
RMSE is 1142.4362782851972

# Random Forest Regressor

In [33]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
rfr=RandomForestRegressor(n_estimators=300,random_state=46)
rfr.fit(x_train,y_train)
rfr.score(x_train,y_train)*100

93.82934706628781

In [35]:
y_pred=rfr.predict(x_test)

In [36]:
y_pred

array([4450.55119667, 2064.65467733, 3978.18385133, ..., 2960.07134267,
       2515.46341867, 1823.639516  ])

# DecisionTreeRegressor

In [38]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(max_depth=15,min_samples_leaf=100)
dtr.fit(x_train,y_train)
dtr_pred=dtr.predict(x_test)

In [40]:
dtr_accuracy=dtr.score(x_train,y_train)*100
dtr_accuracy

59.99769626237321

dtr_pred

In [41]:
dtr_pred

array([3655.74299802, 2317.01221186, 4893.49333579, ..., 2875.07307379,
       3144.03796643, 1699.81334026])

so, here we find  Random Forest Regressor gives us best score. thats why we will go ahead with this regressor algorithem.

# Save the model

In [46]:
from sklearn.externals import joblib
joblib.dump(rfr,'BDMS.pkl')

['BDMS.pkl']